//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoGaWebfull.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oder
    {
        public int OderID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> ShipingID { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<bool> IsComfirm { get; set; }
        public Nullable<System.DateTime> ComfirmDate { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelNote { get; set; }
    }
}
